#!/bin/sh
. $HOME/.nvm/nvm.sh
env
git --work-tree=/var/www/song-quotes.carlescapell.me/public_html/ --git-dir=/var/www/song-quotes.carlescapell.me/.git checkout -f
cd /var/www/song-quotes.carlescapell.me/public_html
npm install
npm run grunt
forever stopall