#!/usr/bin/env bash

set -u
set -e

export NODE_VERSION="8.9.3"

. $HOME/.nvm/nvm.sh
nvm use $NODE_VERSION

git --work-tree=/var/www/song-quotes.carlescapell.me/public_html/ --git-dir=/var/www/song-quotes.carlescapell.me/.git checkout -f
cd /var/www/song-quotes.carlescapell.me/public_html
npm install
npm run grunt
forever stopall
forever start dist/bin/www.js
